name: Get Fishing Reports Every 5 Minutes

on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch: # Allows the workflow to be triggered manually via API

permissions:
  contents: write # Grant write access to the repository contents

jobs:
  fishing-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional, if you have a requirements.txt

      - name: Run script
        run: python ./py-scripts/main.py

      # Configure Git with your details
      - name: Configure Git
        run: |
          git config user.name "hsdehaini"
          git config user.email "hsdehaini@hotmail.com"

      # Commit changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update results [skip ci]" || echo "No changes to commit"

      # Push changes back to the repository
      - name: Push changes
        run: |
          git push origin main
