name: Get Fishing Reports Every 5 Minutes

on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  fishing-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional, if you have a requirements.txt

      - name: Run script
        run: python ./py-scripts/main.py
